main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('savematkul/', views.savematkul, name='savematkul'),
    path('savetugas/<int:pk>', views.savetugas, name='savetugas'),
]

matkulku/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

class MataKuliah(models.Model):  
    nama = models.CharField(max_length=250)
    dosen = models.CharField(max_length=250)
    sks = models.IntegerField()
    deskripsi = models.TextField()
    semester = models.CharField(max_length=9)
    tahun_ajar = models.CharField(max_length=250)

# many to one
class Tugas(models.Model):
    name = models.CharField(max_length=250, default='none')
    deadline = models.DateField()
    mataKuliah = models.ForeignKey(MataKuliah, on_delete=models.CASCADE, default='none', null=True, blank=True)

    class Meta:
        ordering = ['name']

main/forms.py
from django import forms
from .models import MataKuliah, Tugas

import datetime

TAHUN_CHOICES = []
for i in range((datetime.datetime.now().year), 2002, -1):
    TAHUN_CHOICES.append((str(i) +'/'+str(i+1), str(i) +'/'+str(i+1)))

SEMESTER_CHOICES = [('Genap','Genap'), ('Ganjil', 'Ganjil')]

class MataKuliah_Form(forms.ModelForm):
    class Meta:
        model = MataKuliah
        fields = ['nama', 'dosen', 'sks', 'deskripsi', 'semester', 'tahun_ajar']

    nama = forms.CharField(label='Nama Mata Kuliah', label_suffix="", required=True, max_length=250)
    dosen = forms.CharField(label='Dosen', label_suffix="", required=True, max_length=250)
    sks = forms.IntegerField(label='Jumlah SKS', label_suffix="", required=True)
    deskripsi = forms.CharField(label='Deskripsi', label_suffix="", required=True, widget=forms.Textarea(attrs={'type':'text', 'style':'width:75%'}))
    semester = forms.CharField(label='Semester', label_suffix="", required=True, widget=forms.Select(choices=SEMESTER_CHOICES))
    tahun_ajar = forms.CharField(label='Tahun Ajar', label_suffix="", required=True, widget=forms.Select(choices=TAHUN_CHOICES))

class Tugas_Form(forms.ModelForm):
    class Meta:
        model = Tugas
        fields = ['name', 'deadline']

    name = forms.CharField(label='Nama Tugas', label_suffix="", required=True, max_length=250)
    deadline = forms.DateField(label='Deadline', label_suffix="", required=True, widget=forms.DateInput(attrs={'type': 'date'}))

main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import MataKuliah, Tugas
from .forms import MataKuliah_Form, Tugas_Form


# Landing page
def home(request):
    matkul = MataKuliah.objects.all()
    tugas = Tugas.objects.all()
    response = {'matkul' : matkul, 'tugas' : tugas, 'MataKuliah_Form' : MataKuliah_Form, 'Tugas_Form' : Tugas_Form}
    return render(request, 'main/home.html', response)

# save isi form mata kuliah
def savematkul(request):
    form = MataKuliah_Form(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return HttpResponseRedirect('/')
    else:
        form = MataKuliah_Form() 
        return render(request,'main/home.html')

#save isi form tugas
def savetugas(request, pk):
    form = Tugas_Form(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        matkul = get_object_or_404(MataKuliah, pk=pk)           # ambil object mata kuliah dari primary keynya
        new_tugas = Tugas()
        new_tugas.name = form.cleaned_data['name']
        new_tugas.deadline = form.cleaned_data['deadline']
        new_tugas.mataKuliah = matkul
        new_tugas.save()
        return HttpResponseRedirect('/')
    else:
        form = Tugas_Form()
        return render(request,'main/home.html')

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
<div class="container">
  <div class="row">

      <div class="col-sm-12">
          <h1>Tambah Mata Kuliah</h1>
      </div>


      <div class="col col-sm-6">
        <div class="card" style="overflow-y: auto;">
          <div class="card-body">
            <form action="{% url 'main:savematkul' %}" method="POST">
              {% csrf_token %}
              {{ MataKuliah_Form.as_p}} 
              <input class="submit button" type="submit" value="Submit">
            </form>  
          </div>
        </div> 
      </div>


      <div class="col col-sm-6">
        {% if matkul %}
          {% for i in matkul %}
            <div class="card" style="overflow: auto;">
              <div class = "card-body">
                <h2>{{ i.nama }}</h2>
                <table class="table-borderless">
                  <tbody>
                    <tr>
                      <th scope="row">Dosen</th>
                      <td>{{ i.dosen }}</td>
                    </tr>
                    <tr>
                      <th scope="row">Deskripsi</th>
                      <td>{{ i.deskripsi }}</td>
                    </tr>
                    <tr>
                      <th scope="row">Semester</th>
                      <td>{{ i.semester }} {{ i.tahun_ajar }}</td>
                    </tr>
                    <tr>
                      <th scope="row">Tugas</th>
                      <td>
                        <ul>
                          {% for j in i.tugas_set.all %}
                          <li>
                            {{ j.name}} - Deadline: {{j.deadline}}
                          </li>
                          {% endfor %}
                        </ul>
                      </td>
                    </tr>
                  </tbody>
                </table>
                <form action="{% url 'main:savetugas' pk=i.id %}" method="POST">
                  {% csrf_token %}
                  {{ Tugas_Form.as_p }}
                  <button class="submit small-button" type="submit">Tambah</button>
                </form>
              </div>
            </div>
          {% endfor %}
        {% endif %}
      </div>


  </div>
</div>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block meta %}
    {% endblock meta %}
  </head>
  

<body>
  <nav class="navbar navbar-expand-ml navbar-dark"> 
    <h1 style="color: aliceblue;">Matkulku</h1>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto"> 
      </ul> 
    </div>
</nav>

  {% block content %}
  {% endblock content %}

  <footer class="footer" class="py-4 bg-dark text-white-50">
    <div class="">
       <a>&lt;/&gt; with &hearts; by Syifa Rizka Sagita</a>
    </div>
  </footer>
</body>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>  
{% block script %}
{% endblock script %}

</html>